"""Tests for Report Exports + Consent Drafts (Phase 9 + Phase 17).

Covers:
  - HTML report generation (valid case, empty case)
  - Markdown report generation
  - Version metadata
  - Veterinary consent (dog case, non-dog case)
  - Human research consent
  - Unsafe content scanner (dosage, injection, treatment patterns)
  - Sanitize function
  - All 6 API endpoints
"""

from __future__ import annotations

import re

from fastapi.testclient import TestClient

from backend.app.report_exports import (
    UNSAFE_PATTERNS,
    build_human_research_consent,
    build_report_html,
    build_report_markdown,
    build_report_version,
    build_veterinary_consent,
    sanitize_report_text,
    scan_for_unsafe_content,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_case(client: TestClient, species: str = "demo", summary: str = "Export test") -> str:
    resp = client.post("/cases", json={"species": species, "diagnosis_summary": summary})
    assert resp.status_code == 201
    return resp.json()["id"]


def _make_case_with_candidates(client: TestClient, species: str = "demo") -> tuple[str, list[str]]:
    case_id = _make_case(client, species=species)
    for sample_type in ("tumor", "normal", "rna"):
        client.post(f"/cases/{case_id}/samples", json={"sample_type": sample_type})
    variant_ids = []
    for i in range(2):
        v = client.post(
            f"/cases/{case_id}/variants",
            json={"genomic_coordinates": f"chr{i + 1}:1000:A>T", "gene": f"GENE{i}"},
        )
        assert v.status_code == 201
        variant_ids.append(v.json()["id"])
    candidate_ids = []
    for vid in variant_ids:
        c = client.post(
            f"/cases/{case_id}/candidates",
            json={
                "variant_id": vid,
                "prediction_scores": {"binding_affinity": 80.0, "rank": 0.8},
                "expression_evidence": {"tpm": 10.5},
                "mhc_context": "HLA-A*02:01",
            },
        )
        assert c.status_code == 201
        candidate_ids.append(c.json()["id"])
    return case_id, candidate_ids


# ---------------------------------------------------------------------------
# Unit: build_report_html
# ---------------------------------------------------------------------------


def test_html_report_valid_case(client: TestClient) -> None:
    """HTML report for a valid case contains expected sections."""
    from backend.app.db import SessionLocal

    case_id, _ = _make_case_with_candidates(client)
    with SessionLocal() as db:
        html = build_report_html(case_id, db)

    assert "<!DOCTYPE html>" in html
    assert case_id in html
    assert "FoldAgent Case Report" in html
    assert "Candidate Antigens" in html
    assert "Evidence Assessment" in html
    assert "False-Positive Risk" in html
    assert "Source Citations" in html
    assert "Safety Disclaimers" in html
    assert "RESEARCH ONLY" in html


def test_html_report_contains_version_watermark(client: TestClient) -> None:
    """HTML watermark includes version string and hash."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client)
    with SessionLocal() as db:
        html = build_report_html(case_id, db)

    assert "Generated by FoldAgent" in html
    assert "Version" in html


def test_html_report_empty_case(client: TestClient) -> None:
    """Empty case (no candidates) still produces valid HTML with disclaimer."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client)
    with SessionLocal() as db:
        html = build_report_html(case_id, db)

    assert "<!DOCTYPE html>" in html
    assert "No candidate antigens registered" in html
    assert "RESEARCH ONLY" in html


def test_html_report_case_not_found() -> None:
    """Non-existent case returns minimal HTML with 'not found' message."""
    from backend.app.db import SessionLocal

    with SessionLocal() as db:
        html = build_report_html("nonexistent-case-id", db)

    assert "Case not found" in html
    assert "nonexistent-case-id" in html


def test_html_report_candidate_table_rows(client: TestClient) -> None:
    """Candidate table rows include MHC context and binding scores."""
    from backend.app.db import SessionLocal

    case_id, _ = _make_case_with_candidates(client)
    with SessionLocal() as db:
        html = build_report_html(case_id, db)

    assert "HLA-A*02:01" in html
    assert "80.0 nM" in html


# ---------------------------------------------------------------------------
# Unit: build_report_markdown
# ---------------------------------------------------------------------------


def test_markdown_report_valid_case(client: TestClient) -> None:
    """Markdown report for a valid case contains all major sections."""
    from backend.app.db import SessionLocal

    case_id, _ = _make_case_with_candidates(client)
    with SessionLocal() as db:
        md = build_report_markdown(case_id, db)

    assert "# FoldAgent Case Report" in md
    assert "## Case Metadata" in md
    assert "## Candidate Antigens" in md
    assert "## Evidence Assessment" in md
    assert "## False-Positive Risk" in md
    assert "## Source Citations" in md
    assert "## Safety Disclaimers" in md


def test_markdown_report_has_editable_markers(client: TestClient) -> None:
    """Markdown report includes EDITABLE comment markers."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client)
    with SessionLocal() as db:
        md = build_report_markdown(case_id, db)

    editable_sections = re.findall(r"<!-- EDITABLE: [\w-]+ -->", md)
    assert len(editable_sections) >= 5, f"Expected ≥5 editable markers, got {len(editable_sections)}"

    closing_markers = re.findall(r"<!-- /EDITABLE: [\w-]+ -->", md)
    assert len(closing_markers) == len(editable_sections)


def test_markdown_report_case_not_found() -> None:
    """Non-existent case returns a 'not found' Markdown message."""
    from backend.app.db import SessionLocal

    with SessionLocal() as db:
        md = build_report_markdown("ghost-case", db)

    assert "Case Not Found" in md
    assert "ghost-case" in md


def test_markdown_report_empty_candidates(client: TestClient) -> None:
    """Empty case shows placeholder text in candidates section."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client)
    with SessionLocal() as db:
        md = build_report_markdown(case_id, db)

    assert "No candidate antigens registered" in md


def test_markdown_report_version_watermark(client: TestClient) -> None:
    """Markdown report includes version and hash watermark line."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client)
    with SessionLocal() as db:
        md = build_report_markdown(case_id, db)

    assert "Generated by FoldAgent" in md
    assert "Version" in md


# ---------------------------------------------------------------------------
# Unit: build_report_version
# ---------------------------------------------------------------------------


def test_report_version_structure(client: TestClient) -> None:
    """Version metadata has required keys and correct types."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client)
    with SessionLocal() as db:
        meta = build_report_version(case_id, db)

    assert "version" in meta
    assert "hash" in meta
    assert "generated_at" in meta
    assert "format" in meta
    assert meta["format"] == "html"
    assert isinstance(meta["hash"], str)
    assert len(meta["hash"]) == 16


def test_report_version_case_not_found() -> None:
    """Non-existent case returns version with case_found=False."""
    from backend.app.db import SessionLocal

    with SessionLocal() as db:
        meta = build_report_version("no-such-case", db)

    assert meta["case_found"] is False
    assert meta["hash"] is None


def test_report_version_increments_with_candidates(client: TestClient) -> None:
    """Version string encodes candidate count."""
    from backend.app.db import SessionLocal

    case_id, _ = _make_case_with_candidates(client)
    with SessionLocal() as db:
        meta = build_report_version(case_id, db)

    # version format is "1.<report_count>.<candidate_count>"
    parts = meta["version"].split(".")
    assert len(parts) == 3
    assert int(parts[2]) >= 2  # we added 2 candidates


# ---------------------------------------------------------------------------
# Unit: build_veterinary_consent
# ---------------------------------------------------------------------------


def test_veterinary_consent_structure(client: TestClient) -> None:
    """Veterinary consent has required top-level keys."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client, species="dog")
    with SessionLocal() as db:
        result = build_veterinary_consent(case_id, db)

    assert "title" in result
    assert "body" in result
    assert "attestation_fields" in result
    assert "warnings" in result
    assert isinstance(result["attestation_fields"], list)
    assert len(result["attestation_fields"]) >= 5


def test_veterinary_consent_dog_specific(client: TestClient) -> None:
    """Dog case consent uses canine-specific language."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client, species="dog")
    with SessionLocal() as db:
        result = build_veterinary_consent(case_id, db)

    assert result["is_dog_specific"] is True
    assert "canine" in result["body"].lower() or "CanFam4" in result["body"]


def test_veterinary_consent_non_dog_case(client: TestClient) -> None:
    """Non-dog case consent uses generic species language."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client, species="demo")
    with SessionLocal() as db:
        result = build_veterinary_consent(case_id, db)

    assert result["is_dog_specific"] is False
    assert "TEMPLATE ONLY" in result["body"]


def test_veterinary_consent_has_disclaimer(client: TestClient) -> None:
    """Veterinary consent warnings include TEMPLATE ONLY notice."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client, species="dog")
    with SessionLocal() as db:
        result = build_veterinary_consent(case_id, db)

    assert any("TEMPLATE ONLY" in w for w in result["warnings"])
    assert any("dosing" in w.lower() or "injection" in w.lower() for w in result["warnings"])


# ---------------------------------------------------------------------------
# Unit: build_human_research_consent
# ---------------------------------------------------------------------------


def test_human_consent_structure(client: TestClient) -> None:
    """Human research consent has required top-level keys."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client, species="human")
    with SessionLocal() as db:
        result = build_human_research_consent(case_id, db)

    assert "title" in result
    assert "body" in result
    assert "attestation_fields" in result
    assert "warnings" in result
    assert result["irb_required"] is True
    assert result["legal_review_required"] is True


def test_human_consent_strong_irb_warning(client: TestClient) -> None:
    """Human consent body contains strong IRB and legal review warnings."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client, species="human")
    with SessionLocal() as db:
        result = build_human_research_consent(case_id, db)

    body = result["body"]
    assert "IRB" in body
    assert "TEMPLATE ONLY" in body
    assert "NOT" in body


def test_human_consent_warnings_are_strong(client: TestClient) -> None:
    """Human consent warnings list includes CRITICAL and IRB notices."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client, species="human")
    with SessionLocal() as db:
        result = build_human_research_consent(case_id, db)

    warnings_text = " ".join(result["warnings"])
    assert "CRITICAL" in warnings_text or "NOT" in warnings_text
    assert "IRB" in warnings_text


def test_human_consent_includes_withdrawal_rights(client: TestClient) -> None:
    """Human consent template includes withdrawal rights language."""
    from backend.app.db import SessionLocal

    case_id = _make_case(client)
    with SessionLocal() as db:
        result = build_human_research_consent(case_id, db)

    assert "withdraw" in result["body"].lower()


# ---------------------------------------------------------------------------
# Unit: scan_for_unsafe_content
# ---------------------------------------------------------------------------


def test_scan_clean_text_returns_empty() -> None:
    clean = "This is a research coordination artifact listing candidate antigens."
    findings = scan_for_unsafe_content(clean)
    assert findings == []


def test_scan_detects_dosage_pattern() -> None:
    text = "Administer 50 mg dose to the subject subcutaneously."
    findings = scan_for_unsafe_content(text)
    assert len(findings) >= 1
    assert any(f["severity"] == "high" for f in findings)


def test_scan_detects_injection_pattern() -> None:
    text = "inject into subcutaneous tissue using a sterile needle."
    findings = scan_for_unsafe_content(text)
    assert len(findings) >= 1
    assert any("inject" in f["matched_text"].lower() for f in findings)


def test_scan_detects_treatment_protocol() -> None:
    text = "treatment protocol: administer peptide vaccine every 3 weeks."
    findings = scan_for_unsafe_content(text)
    assert len(findings) >= 1


def test_scan_returns_recommendation(text: str = "Administer 10 ml injection") -> None:
    findings = scan_for_unsafe_content(text)
    if findings:
        assert all("recommendation" in f for f in findings)
        assert all("severity" in f for f in findings)
        assert all("matched_text" in f for f in findings)


def test_scan_does_not_duplicate_overlapping_matches() -> None:
    """Overlapping matches should not produce duplicate entries."""
    text = "inject into the patient subcutaneous tissue now"
    findings = scan_for_unsafe_content(text)
    matched_spans = [(f["matched_text"], f["pattern"]) for f in findings]
    # No two entries should have the same matched_text+pattern combination
    assert len(matched_spans) == len(set(matched_spans))


def test_scan_dose_equals_pattern() -> None:
    text = "dose=50 should be rejected"
    findings = scan_for_unsafe_content(text)
    assert len(findings) >= 1


def test_scan_manufacturing_protocol_pattern() -> None:
    text = "Follow the manufacturing protocol steps carefully."
    findings = scan_for_unsafe_content(text)
    assert len(findings) >= 1
    assert any(f["severity"] == "moderate" for f in findings)


# ---------------------------------------------------------------------------
# Unit: sanitize_report_text
# ---------------------------------------------------------------------------


def test_sanitize_replaces_unsafe_content() -> None:
    text = "The treatment protocol: administer 50 mg dose to the patient."
    sanitized = sanitize_report_text(text)
    assert "[REMOVED — consult qualified professional]" in sanitized


def test_sanitize_preserves_clean_text() -> None:
    clean = "This case has 3 candidate antigens identified by computational analysis."
    sanitized = sanitize_report_text(clean)
    assert sanitized == clean


def test_sanitize_returns_string() -> None:
    result = sanitize_report_text("inject into subcutaneous site")
    assert isinstance(result, str)


# ---------------------------------------------------------------------------
# API endpoint tests
# ---------------------------------------------------------------------------


def test_api_html_report_200(client: TestClient) -> None:
    case_id = _make_case(client)
    resp = client.get(f"/cases/{case_id}/report/html")
    assert resp.status_code == 200
    assert "text/html" in resp.headers["content-type"]
    assert "FoldAgent Case Report" in resp.text


def test_api_html_report_404(client: TestClient) -> None:
    resp = client.get("/cases/nonexistent-xyz/report/html")
    assert resp.status_code == 404


def test_api_markdown_report_200(client: TestClient) -> None:
    case_id = _make_case(client)
    resp = client.get(f"/cases/{case_id}/report/markdown")
    assert resp.status_code == 200
    data = resp.json()
    assert data["format"] == "markdown"
    assert "content" in data
    assert "# FoldAgent Case Report" in data["content"]


def test_api_markdown_report_404(client: TestClient) -> None:
    resp = client.get("/cases/nonexistent-xyz/report/markdown")
    assert resp.status_code == 404


def test_api_version_200(client: TestClient) -> None:
    case_id = _make_case(client)
    resp = client.get(f"/cases/{case_id}/report/version")
    assert resp.status_code == 200
    data = resp.json()
    assert "version" in data
    assert "hash" in data
    assert "generated_at" in data
    assert "format" in data


def test_api_version_404(client: TestClient) -> None:
    resp = client.get("/cases/nonexistent-xyz/report/version")
    assert resp.status_code == 404


def test_api_veterinary_consent_200(client: TestClient) -> None:
    case_id = _make_case(client, species="dog")
    resp = client.get(f"/cases/{case_id}/consent/veterinary")
    assert resp.status_code == 200
    data = resp.json()
    assert "title" in data
    assert "body" in data
    assert "warnings" in data
    assert "attestation_fields" in data


def test_api_veterinary_consent_404(client: TestClient) -> None:
    resp = client.get("/cases/nonexistent-xyz/consent/veterinary")
    assert resp.status_code == 404


def test_api_human_research_consent_200(client: TestClient) -> None:
    case_id = _make_case(client, species="human")
    resp = client.get(f"/cases/{case_id}/consent/human-research")
    assert resp.status_code == 200
    data = resp.json()
    assert "title" in data
    assert "body" in data
    assert "warnings" in data
    assert data["irb_required"] is True


def test_api_human_research_consent_404(client: TestClient) -> None:
    resp = client.get("/cases/nonexistent-xyz/consent/human-research")
    assert resp.status_code == 404


def test_api_scan_unsafe_clean_text(client: TestClient) -> None:
    resp = client.post(
        "/reports/scan-unsafe",
        json={"text": "This report contains candidate antigen data only."},
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["safe"] is True
    assert data["count"] == 0
    assert data["findings"] == []


def test_api_scan_unsafe_detects_dosage(client: TestClient) -> None:
    resp = client.post(
        "/reports/scan-unsafe",
        json={"text": "Administer 50 mg dose to the patient intravenously."},
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["safe"] is False
    assert data["count"] >= 1
    assert len(data["findings"]) >= 1
    assert all("severity" in f for f in data["findings"])
    assert all("recommendation" in f for f in data["findings"])


def test_api_scan_unsafe_detects_injection(client: TestClient) -> None:
    resp = client.post(
        "/reports/scan-unsafe",
        json={"text": "inject into subcutaneous tissue at the injection site."},
    )
    assert resp.status_code == 200
    data = resp.json()
    assert data["safe"] is False


def test_api_scan_unsafe_missing_text_field(client: TestClient) -> None:
    resp = client.post("/reports/scan-unsafe", json={})
    assert resp.status_code == 422


def test_api_html_report_with_candidates(client: TestClient) -> None:
    """HTML report for a fully populated case includes candidate data."""
    case_id, _ = _make_case_with_candidates(client)
    resp = client.get(f"/cases/{case_id}/report/html")
    assert resp.status_code == 200
    assert "HLA-A*02:01" in resp.text
    assert "80.0 nM" in resp.text
