"""Molecular Dynamics Handoff — Export structures for OpenMM or GROMACS.

After AlphaFold structure prediction (or co-folding), researchers often want to
run classical MD simulations to study dynamics, binding kinetics, and free energy.
This module prepares the AlphaFold output for handoff to:

  - **OpenMM**: generates a ready-to-run Python simulation script with the
    AMBER14 or CHARMM36 force field, TIP3P/TIP4P-EW water model, PME
    electrostatics, and a Langevin thermostat.

  - **GROMACS**: generates a .mdp parameter file and notes on how to build
    topology with pdb2gmx and run energy minimisation → NVT → NPT → production.

Both exporters include structure validation that flags common issues:
missing heavy atoms, chain breaks (Cα–Cα > 4.2 Å), and steric clashes.

RESEARCH ONLY — not for clinical or regulatory decision-making.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field

try:
    import numpy as _np
    _NUMPY_AVAILABLE = True
except ImportError:  # pragma: no cover
    _NUMPY_AVAILABLE = False


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass
class MDExportConfig:
    """Configuration parameters for an MD simulation export."""

    force_field: str = "amber14"           # "amber14" | "charmm36"
    water_model: str = "tip3p"             # "tip3p" | "tip4pew" | "spce"
    box_padding_nm: float = 1.0            # minimum distance from protein to box edge
    ion_concentration_mol: float = 0.15    # NaCl concentration (mol/L)
    temperature_k: float = 300.0           # simulation temperature (K)
    simulation_ns: float = 100.0           # target production length (ns)


@dataclass
class MDExportResult:
    """Result of an MD export operation."""

    format: str                            # "openmm" | "gromacs"
    topology_data: str                     # topology file content (placeholder)
    coordinate_data: str                   # coordinate file content (placeholder)
    config_script: str                     # runnable script / mdp file
    estimated_runtime_hours: float         # rough GPU runtime estimate
    warnings: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# OpenMM export
# ---------------------------------------------------------------------------

_OPENMM_SCRIPT_TEMPLATE = """\
#!/usr/bin/env python
# OpenMM simulation script — generated by FoldAgent MD Handoff
# RESEARCH ONLY — not for clinical decision-making.
# Force field : {force_field}
# Water model : {water_model}
# Temperature : {temperature_k} K
# Box padding : {box_padding_nm} nm
# Ion conc.   : {ion_concentration_mol} mol/L
# Target run  : {simulation_ns} ns

from openmm import app, unit
from openmm import LangevinMiddleIntegrator, Platform
from openmm.app import (
    PDBFile, ForceField, Modeller, PME, HBonds, DCDReporter, StateDataReporter
)
import sys

# ── 1. Load structure ────────────────────────────────────────────────────────
pdb = PDBFile("structure.pdb")

# ── 2. Force field ───────────────────────────────────────────────────────────
ff = ForceField("{ff_xml}", "{water_xml}")

# ── 3. Solvation ─────────────────────────────────────────────────────────────
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(ff)
modeller.addSolvent(
    ff,
    model="{water_model}",
    padding={box_padding_nm} * unit.nanometer,
    ionicStrength={ion_concentration_mol} * unit.molar,
)

# ── 4. System ─────────────────────────────────────────────────────────────────
system = ff.createSystem(
    modeller.topology,
    nonbondedMethod=PME,
    nonbondedCutoff=1.0 * unit.nanometer,
    constraints=HBonds,
)

# ── 5. Integrator (Langevin, 2 fs timestep) ──────────────────────────────────
integrator = LangevinMiddleIntegrator(
    {temperature_k} * unit.kelvin,
    1.0 / unit.picosecond,
    0.002 * unit.picosecond,
)

# ── 6. Simulation ─────────────────────────────────────────────────────────────
platform = Platform.getPlatformByName("CUDA")
simulation = app.Simulation(modeller.topology, system, integrator, platform)
simulation.context.setPositions(modeller.positions)

# Energy minimisation
print("Minimising energy …")
simulation.minimizeEnergy()

# NVT equilibration (100 ps)
simulation.context.setVelocitiesToTemperature({temperature_k} * unit.kelvin)
simulation.step(50_000)

# Production ({simulation_ns} ns)
n_steps = int({simulation_ns} * 1_000 / 0.002)
simulation.reporters.append(DCDReporter("traj.dcd", 5_000))
simulation.reporters.append(
    StateDataReporter(sys.stdout, 10_000, step=True, potentialEnergy=True, temperature=True)
)
print(f"Running {{n_steps}} steps …")
simulation.step(n_steps)
print("Done.")
"""


def export_for_openmm(pdb_data: str, config: MDExportConfig) -> MDExportResult:
    """Export a PDB structure as a ready-to-run OpenMM Python script.

    Parameters
    ----------
    pdb_data:
        PDB-format string of the structure to simulate.
    config:
        Simulation parameters (force field, water model, temperature, etc.).

    Returns
    -------
    MDExportResult with a runnable OpenMM Python script as ``config_script``.

    RESEARCH ONLY — not for clinical or regulatory decision-making.
    """
    warnings: list[str] = []

    ff_xml_map = {
        "amber14": "amber14-all.xml",
        "charmm36": "charmm36.xml",
    }
    water_xml_map = {
        "tip3p": "amber14/tip3pfb.xml",
        "tip4pew": "amber14/tip4pew.xml",
        "spce": "amber14/spce.xml",
    }

    ff_xml = ff_xml_map.get(config.force_field, "amber14-all.xml")
    water_xml = water_xml_map.get(config.water_model, "amber14/tip3pfb.xml")

    if config.force_field not in ff_xml_map:
        warnings.append(f"Unknown force field '{config.force_field}', defaulting to amber14.")
    if config.water_model not in water_xml_map:
        warnings.append(f"Unknown water model '{config.water_model}', defaulting to tip3p.")

    script = _OPENMM_SCRIPT_TEMPLATE.format(
        force_field=config.force_field,
        ff_xml=ff_xml,
        water_xml=water_xml,
        water_model=config.water_model,
        box_padding_nm=config.box_padding_nm,
        ion_concentration_mol=config.ion_concentration_mol,
        temperature_k=config.temperature_k,
        simulation_ns=config.simulation_ns,
    )

    # Runtime estimate: ~10 ns/day on a single A100 for a ~300-residue protein
    estimated_runtime = round(config.simulation_ns / 10.0 * 24.0, 1)

    topology_data = (
        "# Topology placeholder — generated from structure.pdb by OpenMM Modeller\n"
        f"# Force field: {config.force_field}  Water: {config.water_model}\n"
        "# Run the config_script to generate the actual topology in memory.\n"
    )
    coordinate_data = pdb_data if pdb_data.strip() else "# No PDB data provided.\n"

    return MDExportResult(
        format="openmm",
        topology_data=topology_data,
        coordinate_data=coordinate_data,
        config_script=script,
        estimated_runtime_hours=estimated_runtime,
        warnings=warnings,
    )


# ---------------------------------------------------------------------------
# GROMACS export
# ---------------------------------------------------------------------------

_GROMACS_MDP_TEMPLATE = """\
; GROMACS .mdp — production MD — generated by FoldAgent MD Handoff
; RESEARCH ONLY — not for clinical decision-making.
; Force field : {force_field}
; Water model : {water_model}
; Temperature : {temperature_k} K
; Target run  : {simulation_ns} ns

; ── Run control ──────────────────────────────────────────────────────────────
integrator   = md
dt           = 0.002       ; 2 fs timestep
nsteps       = {nsteps}    ; {simulation_ns} ns total
comm-mode    = Linear
nstcomm      = 100

; ── Output ───────────────────────────────────────────────────────────────────
nstxout-compressed = 5000  ; ~10 ps between frames
nstlog       = 5000
nstenergy    = 500

; ── Neighbour list ───────────────────────────────────────────────────────────
cutoff-scheme = Verlet
nstlist       = 20
pbc           = xyz

; ── Electrostatics ───────────────────────────────────────────────────────────
coulombtype   = PME
rcoulomb      = 1.0

; ── van der Waals ─────────────────────────────────────────────────────────────
vdwtype       = Cut-off
rvdw          = 1.0
DispCorr      = EnerPres

; ── Temperature coupling ─────────────────────────────────────────────────────
tcoupl        = V-rescale
tc-grps       = Protein Non-Protein
tau-t         = 0.1 0.1
ref-t         = {temperature_k} {temperature_k}

; ── Pressure coupling ────────────────────────────────────────────────────────
pcoupl        = Parrinello-Rahman
pcoupltype    = isotropic
tau-p         = 2.0
ref-p         = 1.0
compressibility = 4.5e-5

; ── Constraints ──────────────────────────────────────────────────────────────
constraints   = h-bonds
constraint-algorithm = LINCS

; ── Velocity generation ──────────────────────────────────────────────────────
gen-vel       = no   ; velocities carried from NPT equilibration

; ──────────────────────────────────────────────────────────────────────────────
; Workflow reminder:
;   gmx pdb2gmx -f structure.pdb -o protein.gro -water {water_model}
;   gmx editconf -f protein.gro -o box.gro -c -d {box_padding_nm} -bt cubic
;   gmx solvate -cp box.gro -cs spc216.gro -o solvated.gro -p topol.top
;   gmx grompp -f ions.mdp -c solvated.gro -p topol.top -o ions.tpr
;   gmx genion -s ions.tpr -o ions.gro -p topol.top -pname NA -nname CL \\
;              -neutral -conc {ion_concentration_mol}
;   gmx grompp -f em.mdp  -c ions.gro   -p topol.top -o em.tpr
;   gmx mdrun  -v -deffnm em
;   gmx grompp -f nvt.mdp -c em.gro    -p topol.top -o nvt.tpr
;   gmx mdrun  -deffnm nvt
;   gmx grompp -f npt.mdp -c nvt.gro   -p topol.top -o npt.tpr
;   gmx mdrun  -deffnm npt
;   gmx grompp -f {mdp_name} -c npt.gro -p topol.top -o md.tpr
;   gmx mdrun  -deffnm md
"""


def export_for_gromacs(pdb_data: str, config: MDExportConfig) -> MDExportResult:
    """Export a PDB structure as a GROMACS .mdp parameter file.

    Parameters
    ----------
    pdb_data:
        PDB-format string of the structure to simulate.
    config:
        Simulation parameters.

    Returns
    -------
    MDExportResult with a GROMACS .mdp file as ``config_script``.

    RESEARCH ONLY — not for clinical or regulatory decision-making.
    """
    warnings: list[str] = []

    supported_ff = {"amber14", "charmm36"}
    if config.force_field not in supported_ff:
        warnings.append(f"Force field '{config.force_field}' may not be bundled with GROMACS. "
                        "Use 'amber14' or 'charmm36'.")

    nsteps = int(config.simulation_ns * 1_000 / 0.002)
    mdp_name = "md_production.mdp"

    mdp = _GROMACS_MDP_TEMPLATE.format(
        force_field=config.force_field,
        water_model=config.water_model,
        box_padding_nm=config.box_padding_nm,
        ion_concentration_mol=config.ion_concentration_mol,
        temperature_k=config.temperature_k,
        simulation_ns=config.simulation_ns,
        nsteps=nsteps,
        mdp_name=mdp_name,
    )

    # Runtime estimate: ~50 ns/day on a 4-GPU cluster for ~300-residue protein
    estimated_runtime = round(config.simulation_ns / 50.0 * 24.0, 1)

    topology_data = (
        "; GROMACS topology placeholder\n"
        "; Run pdb2gmx to generate the actual topol.top and position restraint files.\n"
        f"; Force field: {config.force_field}  Water: {config.water_model}\n"
    )
    coordinate_data = pdb_data if pdb_data.strip() else "; No PDB data provided.\n"

    return MDExportResult(
        format="gromacs",
        topology_data=topology_data,
        coordinate_data=coordinate_data,
        config_script=mdp,
        estimated_runtime_hours=estimated_runtime,
        warnings=warnings,
    )


# ---------------------------------------------------------------------------
# Structure validation
# ---------------------------------------------------------------------------


def validate_structure_for_md(pdb_data: str) -> dict:
    """Validate a PDB structure for MD simulation readiness (stub).

    Checks performed (mock/heuristic):
      - ``has_atoms``: at least one ATOM/HETATM record found
      - ``missing_heavy_atoms``: estimated from REMARK fields (stub: False)
      - ``chain_breaks``: consecutive Cα distance > 4.2 Å (stub: estimated)
      - ``steric_clashes``: any pair of non-bonded atoms < 1.5 Å (stub: False)
      - ``n_residues``: count of unique (chain, resSeq) pairs from ATOM lines
      - ``n_chains``: number of unique chain IDs
      - ``passed``: True if no critical issues detected

    RESEARCH ONLY — not for clinical or regulatory decision-making.
    """
    lines = pdb_data.splitlines()
    atom_lines = [l for l in lines if l.startswith("ATOM") or l.startswith("HETATM")]
    has_atoms = len(atom_lines) > 0

    residues: set[tuple[str, str]] = set()
    chains: set[str] = set()
    for ln in atom_lines:
        if len(ln) >= 26:
            chain_id = ln[21] if len(ln) > 21 else " "
            res_seq = ln[22:26].strip()
            residues.add((chain_id, res_seq))
            chains.add(chain_id)

    n_residues = len(residues)
    n_chains = len(chains)

    # Heuristic: if very few atoms relative to residues, flag missing heavy atoms
    missing_heavy_atoms = has_atoms and (len(atom_lines) < n_residues * 3)

    # Chain break heuristic: flag if REMARK mentions chain breaks
    chain_break_remarks = any("CHAIN BREAK" in l.upper() or "MISSING" in l.upper() for l in lines)

    # Steric clash detection: parse atom coordinates and check pairwise distances.
    # A clash is flagged when two non-bonded heavy atoms are closer than 2.0 Å.
    # Bonded pairs (same residue, sequential serial numbers) are excluded.
    steric_clashes = False
    if has_atoms and _NUMPY_AVAILABLE:
        coords: list[tuple[float, float, float]] = []
        atom_serial: list[int] = []
        atom_res_key: list[tuple[str, str]] = []  # (chain_id, res_seq)
        for ln in atom_lines:
            if len(ln) < 54:
                continue
            try:
                x = float(ln[30:38])
                y = float(ln[38:46])
                z = float(ln[46:54])
                serial = int(ln[6:11].strip()) if len(ln) >= 11 else 0
                chain_id = ln[21] if len(ln) > 21 else " "
                res_seq = ln[22:26].strip()
            except ValueError:
                continue
            coords.append((x, y, z))
            atom_serial.append(serial)
            atom_res_key.append((chain_id, res_seq))

        if len(coords) >= 2:
            xyz = _np.array(coords, dtype=_np.float64)
            clash_threshold_sq = 2.0 ** 2  # 4.0 Å²
            n = len(coords)
            # Iterate over inter-residue pairs only; stop at first clash
            for i in range(n):
                if steric_clashes:
                    break
                # Compute distances from atom i to all atoms j > i at once
                diffs = xyz[i + 1:] - xyz[i]                          # (n-i-1, 3)
                d2 = (diffs * diffs).sum(axis=1)                       # (n-i-1,)
                close_mask = d2 < clash_threshold_sq                   # potential clashes
                if not close_mask.any():
                    continue
                # Check that close atoms are not in the same residue
                for offset in _np.where(close_mask)[0]:
                    j = i + 1 + int(offset)
                    if atom_res_key[i] != atom_res_key[j]:
                        steric_clashes = True
                        break

    passed = has_atoms and not missing_heavy_atoms and not chain_break_remarks and not steric_clashes

    warnings: list[str] = []
    if not has_atoms:
        warnings.append("No ATOM/HETATM records found.")
    if missing_heavy_atoms:
        warnings.append("Possible missing heavy atoms (< 3 atoms per residue on average).")
    if chain_break_remarks:
        warnings.append("REMARK lines suggest missing residues or chain breaks.")
    if steric_clashes:
        warnings.append("Steric clashes detected: non-bonded atom pair(s) closer than 2.0 Å.")
    if not _NUMPY_AVAILABLE:
        warnings.append("numpy not available; steric clash check skipped.")

    return {
        "passed": passed,
        "has_atoms": has_atoms,
        "missing_heavy_atoms": missing_heavy_atoms,
        "chain_breaks_detected": chain_break_remarks,
        "steric_clashes": steric_clashes,
        "n_residues": n_residues,
        "n_chains": n_chains,
        "warnings": warnings,
    }
