"""Multi-epitope vaccine design mode for NeoVax-Agent.

RESEARCH USE ONLY. Not for human or animal clinical use.
All outputs require clinical trial validation, regulatory approval, and expert oversight.
This module provides computational scaffolding only — it does not constitute
medical advice, veterinary advice, or treatment recommendations.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from sqlalchemy.orm import Session

VACCINE_DESIGN_DISCLAIMER = (
    "RESEARCH ONLY — NOT FOR HUMAN OR ANIMAL USE. "
    "All vaccine constructs generated by this tool are computational research artifacts. "
    "Clinical use requires preclinical studies, regulatory submission, ethics board review, "
    "and approval by qualified medical/veterinary professionals. "
    "This tool does not provide dosing, manufacturing, or administration instructions."
)

# ---------------------------------------------------------------------------
# Linker types
# ---------------------------------------------------------------------------

class LinkerType(str, Enum):
    GPGPG = "GPGPG"
    AAY = "AAY"
    KK = "KK"
    EAAAK = "EAAAK"
    GGGGS = "GGGGS"


# tPA signal peptide — commonly used in recombinant vaccine constructs
_TPA_SIGNAL_PEPTIDE = "MDAMKRGLCCVLLLCGAVFVSPSAS"

# Average amino acid molecular weight in kDa
_AVG_RESIDUE_MW_KDA = 0.11


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------

@dataclass
class EpitopeCandidate:
    sequence: str
    source: str  # gene or pathogen name
    epitope_type: str  # b_cell | t_cell_mhci | t_cell_mhcii
    score: float
    conservation: float  # 0-1


@dataclass
class VaccineConstruct:
    full_sequence: str
    epitopes: list[EpitopeCandidate]
    linkers: list[str]
    total_length: int
    estimated_mw_kda: float
    signal_peptide: str | None


@dataclass
class BCellEpitope:
    start: int
    end: int
    sequence: str
    surface_accessibility: float
    hydrophilicity: float
    antigenicity_score: float


@dataclass
class ConservationResult:
    epitope_sequence: str
    conservation_score: float  # 0-1
    variant_positions: list[int]
    strain_coverage: float  # fraction of reference strains containing epitope


@dataclass
class PathogenTarget:
    pathogen_name: str
    protein_name: str
    uniprot_id: str
    known_epitopes: list[str]
    vaccine_type: str  # subunit | mRNA | live-attenuated | viral-vector


@dataclass
class mRNAConstruct:
    coding_sequence: str
    utr5: str
    utr3: str
    poly_a_length: int
    gc_content: float
    codon_adaptation_index: float


# ---------------------------------------------------------------------------
# Amino acid property tables
# ---------------------------------------------------------------------------

# Parker hydrophilicity scale (Parker et al., 1986)
PARKER_HYDROPHILICITY: dict[str, float] = {
    "A": -0.5, "R": 3.0, "N": 0.2, "D": 3.0, "C": -1.0,
    "Q": 0.2, "E": 3.0, "G": 0.0, "H": -0.5, "I": -1.8,
    "L": -1.8, "K": 3.0, "M": -1.3, "F": -2.5, "P": 0.0,
    "S": 0.3, "T": -0.4, "W": -3.4, "Y": -2.3, "V": -1.5,
}

# Emini surface accessibility values (Emini et al., 1985)
EMINI_SURFACE_ACCESSIBILITY: dict[str, float] = {
    "A": 0.49, "R": 0.95, "N": 0.81, "D": 0.83, "C": 0.26,
    "Q": 0.84, "E": 0.84, "G": 0.48, "H": 0.66, "I": 0.34,
    "L": 0.40, "K": 1.05, "M": 0.48, "F": 0.42, "P": 0.75,
    "S": 0.70, "T": 0.71, "W": 0.51, "Y": 0.76, "V": 0.36,
}

# Kolaskar-Tongaonkar antigenicity scale (Kolaskar & Tongaonkar, 1990)
_KOLASKAR_ANTIGENICITY: dict[str, float] = {
    "A": 1.064, "R": 0.873, "N": 0.776, "D": 0.924, "C": 1.020,
    "Q": 0.931, "E": 0.932, "G": 0.874, "H": 1.105, "I": 1.152,
    "L": 1.250, "K": 0.930, "M": 0.826, "F": 1.091, "P": 0.922,
    "S": 1.012, "T": 1.086, "W": 0.893, "Y": 0.909, "V": 1.161,
}


def _safe_aa_lookup(table: dict[str, float], aa: str) -> float:
    """Return property value for amino acid; default to 0.5 for unknowns."""
    return table.get(aa.upper(), 0.5)


# ---------------------------------------------------------------------------
# B-cell epitope prediction
# ---------------------------------------------------------------------------

def predict_b_cell_epitopes(
    protein_sequence: str,
    window_min: int = 12,
    window_max: int = 20,
    top_n: int = 5,
) -> list[BCellEpitope]:
    """Predict B-cell epitopes using sliding-window property scoring.

    Combines Parker hydrophilicity, Emini surface accessibility, and
    Kolaskar-Tongaonkar antigenicity. Returns top_n scored windows.

    STUB IMPLEMENTATION — not calibrated for clinical use.
    """
    seq = protein_sequence.upper()
    n = len(seq)
    if n < window_min:
        return []

    candidates: list[tuple[float, BCellEpitope]] = []

    window = (window_min + window_max) // 2  # fixed midpoint window for simplicity

    for i in range(n - window + 1):
        subseq = seq[i : i + window]

        hydro = sum(_safe_aa_lookup(PARKER_HYDROPHILICITY, aa) for aa in subseq) / window
        surf = sum(_safe_aa_lookup(EMINI_SURFACE_ACCESSIBILITY, aa) for aa in subseq) / window
        antig = sum(_safe_aa_lookup(_KOLASKAR_ANTIGENICITY, aa) for aa in subseq) / window

        # Combined score: high hydrophilicity + high surface + high antigenicity
        combined = (hydro + 3.4) / 6.8 * 0.4 + surf / 1.05 * 0.3 + (antig - 0.7) / 0.6 * 0.3

        epitope = BCellEpitope(
            start=i,
            end=i + window,
            sequence=subseq,
            surface_accessibility=round(surf, 4),
            hydrophilicity=round(hydro, 4),
            antigenicity_score=round(combined, 4),
        )
        candidates.append((combined, epitope))

    candidates.sort(key=lambda x: x[0], reverse=True)
    return [ep for _, ep in candidates[:top_n]]


# ---------------------------------------------------------------------------
# Conservation analysis
# ---------------------------------------------------------------------------

# Short reference sequence fragments for demo purposes only
REFERENCE_STRAINS: dict[str, str] = {
    "SARS-CoV-2_spike_RBD": (
        "NITNLCPFGEVFNATRFASVYAWNRKRISNCVADYSVLYNSASFSTFKCYGVSPTKLNDLCFTNVYADSFVIRGDEVRQIAPGQTGKIADYNYKLPDDFTGCVIAWNSNNLDSKVGGNYNYLYRLFRKSNLKPFERDISTEIYQAGSTPCNGVEGFNCYFPLQSYGFQPTNGVGYQPYRVVVLSFELLHAPATVCGPKKSTNLVKNKCVNFNFNGLTGTGVLTESNKKFLPFQQFGRDIADTTDAVRDPQTLEILDITPCSFGGVSVITPGTNTSNQVAVLYQDVNCTEVPVAIHADQLTPTWRVYSTGSNVFQTRAGCLIGAEHVNNSYECDIPIGAGICASYQTQTNSPRRARSVASQSIIAYTMSLGAENSVAYSNNSIAIPTNFTISVTTEILPVSMTKTSVDCTMYICGDSTECSNLLLQYGSFCTQLNRALTGIAVEQDKNTQEVFAQVKQIYKTPPIKDFGGFNFSQILPDPSKPSKRSFIEDLLFNKVTLADAGFIKQYGDCLGDIAARDLICAQKFNGLTVLPPLLTDEMIAQYTSALLAGTITSGWTFGAGAALQIPFAMQMAYRFNGIGVTQNVLYENQKLIANQFNSAIGKIQDSLSSTASALGKLQDVVNQNAQALNTLVKQLSSNFGAISSVLNDILSRLDKVEAEVQIDRLITGRLQSLQTYVTQQLIRAAEIRASANLAATKMSECVLGQSKRVDFCGKGYHLMSFPQSAPHGVVFLHVTYVPAQEKNFTTAPAICHDGKAHFPREGVFVSNGTHWFVTQRNFYEPQIITTDNTFVSGNCDVVIGIVNNTVYDPLQPELDSFKEELDKYFKNHTSPDVDLGDISGINASVVNIQKEIDRLNEVAKNLNESLIDLQELGKYEQYIKWPWYIWLGFIAGLIAIVMVTIMLCCMTSCCSCLKGCCSCGSCCKFDEDDSEPVLKGVKLHYT"
    ),
    "Influenza_HA_H3": (
        "MKTIIALSNILYCFQQNLPKNIQKTYQSEVFNKTNATLYCKHNGITSKVNISDKIYGDSTAKDRITIVDGWAFTTLSKHPNDAINFESNGNFIAPEYAYRIVNKKNKTATNPLTIEQYTNIINKTNDKIESTPNLTKTYVKLNTTDKAVQNFDKAYPFESNTTSGKLHLDSKYLDNHTNPKYVKSLKLCEAGWLLSNKGTYSGNCSNPNRNQDEDGFLSLGTGTIPMMAFNNLTSTVLGVSILNIGRMVDGFEWGNSFGGWSYIVKHPNGPDKACLKAGDSSSFYVNGTNYYSVSSKLVSVGWSASKSISFCQLNDALLGNKKITQNATLNRYVNHVSGTQHSTKEQESGLRSLISFESSCYPYDVPDYASLFIYEKVLPQLWLTDSGSCPIIHDRNYTVSYQNDLNYNKPNKMLPKLYGSGPASGNRETIKGVTASCSHNGKSSFYRNLLWLTGKNGLYPNLSKSYANNKEKEVLVLWGIHHPSNIAEKEIPFDNQIYRIVEKKISSYVIVHRDIVENGRGLQRRNYYDQSGERPQAPRGQSSGIASIGYSYGANIAKGFGSGIITSNASMDECDAKCQTPQGAINSSLPFQNVHPVTIGECPKYVKSTKLRLATGLRNVPQIESRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDEITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRSQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREEIDGVKLESTRIYQILAIYSTVASSLVLVVSLGAISFWMCSNGSLQCRICI"
    ),
    "HIV_gp120_fragment": (
        "MRVKEKYQHLWRWGWRWGTMLLGMLMICSATEKLWVTVYYGVPVWKEATTTLFCASDAKAYDTEVHNVWATHACVPTDPNPQEVVLVNVTENFNMWKNDMVEQMHEDIISLWDQSLKPCVKLTPLCVSLKCTDLKNDTNTNSSSGRMIMEKGEIKNCSFNISTSIRGKVQKEYAFFYKLDIIPIDNDTTSYKLTSCNTSVITQACPKVSFEPIPIHYCAPAGFAILKCNNKTFNGTGPCTNVSTVQCTHGIRPVVSTQLLLNGSLAEEEVVIRSVNFTDNAKTIIVQLNTSVEINCTRPNNNTRKRIRIQRGPGRAFVTIGKIGNMRQAHCNISRAKWNNTLKQIASKLREQFGNNKTIIFKQSSGGDPEIVTHSFNCGGEFFYCNSTQLFNSTWFNSTWSTEGSNNTEGSDTITLPCRIKQIINMWQKVGKAMYAPPISGQIRCSSNITGLLLTRDGGNSNNESEIFRPGGGDMRDNWRSELYKYKVVKIEPLGVAPTKAKRRVVQREKRAVGIGALFLGFLGAAGSTMGAASMTLTVQARQLLSGIVQQQNNLLRAIEAQQHLLQLTVWGIKQLQARILAVERYLKDQQLLGIWGCSGKLICTTAVPWNASWSNKSLEQIWNHTTWMEWDREINNYTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWFNITNWLWYIKLFIMIVGGLVGLRIVFAVLSIVNRVRQGYSPLSFQTHLPIPRGPDRPEGIEEEGGERDRDRSIRLVNGSLALIWDDLRSLCLFSYHRLRDLLLIVTRIVELLGRRGWEALKYWWNLLQYWSQELKNSAVSLLNATAIAVAEGTDRVIEVVQGACRAIRHIPRRIRQGLERILL"
    ),
}


def analyze_epitope_conservation(
    epitope: str,
    reference_sequences: list[str],
    max_mismatches: int = 2,
) -> ConservationResult:
    """Analyse how conserved an epitope is across reference sequences.

    Checks exact match or ≤ max_mismatches substitutions using sliding window.
    """
    epitope_upper = epitope.upper()
    ep_len = len(epitope_upper)

    if not reference_sequences or ep_len == 0:
        return ConservationResult(
            epitope_sequence=epitope,
            conservation_score=0.0,
            variant_positions=[],
            strain_coverage=0.0,
        )

    hits = 0
    all_variant_positions: list[int] = []

    for ref in reference_sequences:
        ref_upper = ref.upper()
        best_mismatches = ep_len + 1  # worse than any real match
        best_variant_pos: list[int] = []

        for i in range(len(ref_upper) - ep_len + 1):
            window = ref_upper[i : i + ep_len]
            mismatches = sum(a != b for a, b in zip(epitope_upper, window))
            if mismatches < best_mismatches:
                best_mismatches = mismatches
                best_variant_pos = [j for j, (a, b) in enumerate(zip(epitope_upper, window)) if a != b]

        if best_mismatches <= max_mismatches:
            hits += 1
            all_variant_positions.extend(best_variant_pos)

    # Deduplicate variant positions
    unique_positions = sorted(set(all_variant_positions))
    strain_coverage = hits / len(reference_sequences)
    # Conservation score penalises variant positions
    if strain_coverage == 0.0:
        conservation_score = 0.0
    else:
        position_penalty = len(unique_positions) / ep_len * 0.3
        conservation_score = max(0.0, strain_coverage - position_penalty)

    return ConservationResult(
        epitope_sequence=epitope,
        conservation_score=round(conservation_score, 4),
        variant_positions=unique_positions,
        strain_coverage=round(strain_coverage, 4),
    )


# ---------------------------------------------------------------------------
# Multi-epitope construct builder
# ---------------------------------------------------------------------------

def build_multi_epitope_construct(
    epitopes: list[EpitopeCandidate],
    linker: str = "GPGPG",
    add_signal_peptide: bool = True,
) -> VaccineConstruct:
    """Concatenate epitope sequences with linkers into a multi-epitope construct.

    Optionally prepends the tPA signal peptide for secretory expression.
    Estimates molecular weight at 0.11 kDa per residue.
    """
    if not epitopes:
        raise ValueError("At least one epitope is required to build a construct.")

    linker_str = linker.upper() if isinstance(linker, str) else linker.value

    parts = [ep.sequence.upper() for ep in epitopes]
    joined = linker_str.join(parts)

    signal = _TPA_SIGNAL_PEPTIDE if add_signal_peptide else None
    full_sequence = (signal + joined) if signal else joined

    linkers_used = [linker_str] * (len(parts) - 1)

    total_length = len(full_sequence)
    estimated_mw = round(total_length * _AVG_RESIDUE_MW_KDA, 3)

    return VaccineConstruct(
        full_sequence=full_sequence,
        epitopes=epitopes,
        linkers=linkers_used,
        total_length=total_length,
        estimated_mw_kda=estimated_mw,
        signal_peptide=signal,
    )


# ---------------------------------------------------------------------------
# Pathogen database
# ---------------------------------------------------------------------------

PATHOGEN_DATABASE: dict[str, list[PathogenTarget]] = {
    "SARS-CoV-2": [
        PathogenTarget(
            pathogen_name="SARS-CoV-2",
            protein_name="Spike RBD",
            uniprot_id="P0DTC2",
            known_epitopes=["YQDVNCTEV", "SKVGGNYNYLYRLFRKSNLK", "FIAGLIAIVMVTI"],
            vaccine_type="mRNA",
        ),
        PathogenTarget(
            pathogen_name="SARS-CoV-2",
            protein_name="Nucleocapsid",
            uniprot_id="P0DTC9",
            known_epitopes=["SPRWYFYYL", "KTFPPTEPKKDKKKK", "AGLPYGANKDGIIWVATEGALNTPK"],
            vaccine_type="subunit",
        ),
    ],
    "Influenza": [
        PathogenTarget(
            pathogen_name="Influenza",
            protein_name="Hemagglutinin (HA)",
            uniprot_id="P03452",
            known_epitopes=["YPYDVPDYA", "SVSSFERFEIFPKE", "HNTNGVTAACSHEGKSSFYRNLLWLTK"],
            vaccine_type="subunit",
        ),
        PathogenTarget(
            pathogen_name="Influenza",
            protein_name="Neuraminidase (NA)",
            uniprot_id="P03468",
            known_epitopes=["ILRTQSECV", "DTVNWTSNSIVVICGSRSL", "PNQMLPTDVQILYQQNSLK"],
            vaccine_type="subunit",
        ),
    ],
    "HIV": [
        PathogenTarget(
            pathogen_name="HIV",
            protein_name="gp120",
            uniprot_id="P04578",
            known_epitopes=["INCTRPNNNTRKR", "SKVGGNYNYL", "KQIINMWQKVGK"],
            vaccine_type="subunit",
        ),
        PathogenTarget(
            pathogen_name="HIV",
            protein_name="gp41",
            uniprot_id="P04578",
            known_epitopes=["LLELDKWASLWNWF", "NNLLRAIEAQQHLL", "WGCSGKLICTTAVPWNAS"],
            vaccine_type="viral-vector",
        ),
    ],
    "Malaria": [
        PathogenTarget(
            pathogen_name="Malaria",
            protein_name="Circumsporozoite protein (CSP)",
            uniprot_id="P19597",
            known_epitopes=["NANPNANPNANP", "DPNANPNVDPNANPNV", "EYLNKIQNSLSTEWSPCSVTCGNGIQVRIKPGSANKPKDELDYENDIEKKICKMEKCSSVFNVVNSSIGLIMK"],
            vaccine_type="subunit",
        ),
        PathogenTarget(
            pathogen_name="Malaria",
            protein_name="Apical membrane antigen 1 (AMA1)",
            uniprot_id="Q8I0T5",
            known_epitopes=["YLKDNKYVFQL", "SFDDINDIEKEKICKMEK", "HKSYISSRTDNISTLRSIT"],
            vaccine_type="subunit",
        ),
    ],
    "TB": [
        PathogenTarget(
            pathogen_name="TB",
            protein_name="Antigen 85B (Ag85B)",
            uniprot_id="P71735",
            known_epitopes=["FQDAYNAAGGHNAVF", "DPAVSSAWQSYVFSSM", "QAYRSAGDTASQSVGSMGGSM"],
            vaccine_type="subunit",
        ),
        PathogenTarget(
            pathogen_name="TB",
            protein_name="ESAT-6",
            uniprot_id="P9WNK9",
            known_epitopes=["MTEQQWNFAGIEAAASAIQGNVTSIHSLLDEGKQSLTKLAAAWGGSGSEAYQGVQQKWDATATELNNALQNLARTISEAGKR", "AIQGNVTSIHSLLDEGKQS", "QQWNFAGIEAAASAIQ"],
            vaccine_type="subunit",
        ),
    ],
    "HPV": [
        PathogenTarget(
            pathogen_name="HPV",
            protein_name="E6",
            uniprot_id="P06463",
            known_epitopes=["FAFRDLCIVY", "KLPQLCTELQTTIHD", "YAAFFGDTGHGKRPPR"],
            vaccine_type="mRNA",
        ),
        PathogenTarget(
            pathogen_name="HPV",
            protein_name="E7",
            uniprot_id="P06461",
            known_epitopes=["RAHYNIVTF", "TLGIVCPICSQKP", "MHGDTPTLHEYMLDLQPETTD"],
            vaccine_type="mRNA",
        ),
    ],
    "Ebola": [
        PathogenTarget(
            pathogen_name="Ebola",
            protein_name="Glycoprotein (GP)",
            uniprot_id="Q05320",
            known_epitopes=["IRGFPRCCRFPRL", "TQFPNGLNQPRGF", "GPCAGDFAFKLYPENQITYK"],
            vaccine_type="viral-vector",
        ),
    ],
    "RSV": [
        PathogenTarget(
            pathogen_name="RSV",
            protein_name="Fusion protein (F)",
            uniprot_id="P03420",
            known_epitopes=["NSELLSLINDMPITNDQ", "KKTTKQIQNAQKFMGSSR", "FSTGKPCLKPTKDSSSVITSLGAIVSCYGKTKCTASNKNRGIIKTFSNGCDYVSNKGMDTVSVGNTLYYVNKQEGKSLYVKGEPIINFYDPLVFPSDEFDASISQVNEKINQSLAFIRKSDELLHNVNAGKSTTNIMITTIIIVIIVILLSLIAVGLLLYCKARSTPVTLSKDQLSGINNIAFSN"],
            vaccine_type="subunit",
        ),
    ],
}


def get_pathogen_targets(pathogen: str) -> list[PathogenTarget]:
    """Return all vaccine targets for a given pathogen name (case-insensitive)."""
    for key, targets in PATHOGEN_DATABASE.items():
        if key.lower() == pathogen.lower():
            return targets
    return []


def get_known_epitopes(pathogen: str, protein: str) -> list[str]:
    """Return known epitopes for a specific pathogen+protein combination."""
    targets = get_pathogen_targets(pathogen)
    for t in targets:
        if t.protein_name.lower() == protein.lower():
            return t.known_epitopes
    return []


# ---------------------------------------------------------------------------
# mRNA construct optimization
# ---------------------------------------------------------------------------

# Preferred codon tables (human and dog)
# Each amino acid maps to its most-preferred codon in that species
CODON_TABLES: dict[str, dict[str, str]] = {
    "human": {
        "A": "GCC", "R": "AGG", "N": "AAC", "D": "GAC", "C": "TGC",
        "Q": "CAG", "E": "GAG", "G": "GGC", "H": "CAC", "I": "ATC",
        "L": "CTG", "K": "AAG", "M": "ATG", "F": "TTC", "P": "CCC",
        "S": "AGC", "T": "ACC", "W": "TGG", "Y": "TAC", "V": "GTG",
        "*": "TGA",
    },
    "dog": {
        "A": "GCC", "R": "CGG", "N": "AAC", "D": "GAC", "C": "TGC",
        "Q": "CAG", "E": "GAG", "G": "GGC", "H": "CAC", "I": "ATC",
        "L": "CTG", "K": "AAG", "M": "ATG", "F": "TTC", "P": "CCC",
        "S": "TCC", "T": "ACC", "W": "TGG", "Y": "TAC", "V": "GTG",
        "*": "TGA",
    },
}

_UTR5_PLACEHOLDER = (
    "GGGAAAUAAGAGAGAAAAGAAGAGUAAGAAGAAAUAUAAGAGCCACCAUGGG"
)
_UTR3_PLACEHOLDER = (
    "UGCAUAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
)
_DEFAULT_POLY_A_LENGTH = 120


def _reverse_translate(protein_sequence: str, species: str = "human") -> str:
    """Reverse-translate a protein sequence to coding DNA using preferred codons."""
    codon_table = CODON_TABLES.get(species.lower(), CODON_TABLES["human"])
    codons = []
    for aa in protein_sequence.upper():
        if aa in codon_table:
            codons.append(codon_table[aa])
        elif aa == "X":
            codons.append("NNN")  # unknown amino acid
        # skip gaps/non-standard
    return "".join(codons)


def _gc_content(sequence: str) -> float:
    """Calculate GC content of a nucleotide sequence (0-1)."""
    seq = sequence.upper()
    if not seq:
        return 0.0
    gc = sum(1 for nt in seq if nt in "GC")
    return round(gc / len(seq), 4)


def _estimate_cai(coding_sequence: str, species: str = "human") -> float:
    """Estimate codon adaptation index (simplified — ratio of preferred codons used)."""
    # Since we generate using preferred codons, CAI ≈ 1.0 for our output
    # Real CAI requires full codon usage table comparison
    codon_table = CODON_TABLES.get(species.lower(), CODON_TABLES["human"])
    preferred_codons = set(codon_table.values())
    seq = coding_sequence.upper()
    triplets = [seq[i : i + 3] for i in range(0, len(seq) - 2, 3)]
    if not triplets:
        return 0.0
    hits = sum(1 for c in triplets if c in preferred_codons)
    return round(hits / len(triplets), 4)


def optimize_mrna_construct(
    protein_sequence: str,
    species: str = "human",
    poly_a_length: int = _DEFAULT_POLY_A_LENGTH,
) -> mRNAConstruct:
    """Generate an mRNA construct from a protein sequence.

    Reverse-translates using preferred codons, adds 5'/3' UTR placeholders,
    and a poly-A tail.

    PLACEHOLDER — not calibrated for clinical manufacturing.
    """
    coding_seq = _reverse_translate(protein_sequence, species)
    # Add start codon if not already present
    if not coding_seq.startswith("ATG"):
        coding_seq = "ATG" + coding_seq
    # Add stop codon
    stop = CODON_TABLES.get(species.lower(), CODON_TABLES["human"]).get("*", "TGA")
    coding_seq = coding_seq + stop

    gc = _gc_content(coding_seq)
    cai = _estimate_cai(coding_seq, species)

    return mRNAConstruct(
        coding_sequence=coding_seq,
        utr5=_UTR5_PLACEHOLDER,
        utr3=_UTR3_PLACEHOLDER,
        poly_a_length=poly_a_length,
        gc_content=gc,
        codon_adaptation_index=cai,
    )


# ---------------------------------------------------------------------------
# Rapid-response pipeline
# ---------------------------------------------------------------------------

def rapid_response_pipeline(
    pathogen_sequence: str,
    pathogen_name: str,
    top_n_epitopes: int = 5,
    linker: str = "GPGPG",
) -> dict:
    """End-to-end rapid-response vaccine design pipeline.

    Steps:
      1. Predict B-cell epitopes from sequence.
      2. Score epitopes by conservation (self-reference demo).
      3. Build multi-epitope construct from top N.
      4. Optimize mRNA construct.

    RESEARCH ONLY — not for clinical decision-making.
    """
    pipeline_start = time.monotonic()
    results: dict = {"pathogen_name": pathogen_name, "steps": {}, "disclaimer": VACCINE_DESIGN_DISCLAIMER}

    # Step 1: B-cell epitope prediction
    t0 = time.monotonic()
    b_cell_epitopes = predict_b_cell_epitopes(pathogen_sequence, top_n=top_n_epitopes)
    results["steps"]["b_cell_prediction"] = {
        "duration_s": round(time.monotonic() - t0, 4),
        "epitopes_found": len(b_cell_epitopes),
        "epitopes": [
            {
                "sequence": ep.sequence,
                "start": ep.start,
                "end": ep.end,
                "antigenicity_score": ep.antigenicity_score,
                "hydrophilicity": ep.hydrophilicity,
                "surface_accessibility": ep.surface_accessibility,
            }
            for ep in b_cell_epitopes
        ],
    }

    # Step 2: Conservation analysis (self-reference for demo)
    t0 = time.monotonic()
    conservation_results = []
    for ep in b_cell_epitopes:
        cr = analyze_epitope_conservation(ep.sequence, [pathogen_sequence])
        conservation_results.append(cr)
    results["steps"]["conservation_analysis"] = {
        "duration_s": round(time.monotonic() - t0, 4),
        "results": [
            {
                "sequence": cr.epitope_sequence,
                "conservation_score": cr.conservation_score,
                "strain_coverage": cr.strain_coverage,
                "variant_positions": cr.variant_positions,
            }
            for cr in conservation_results
        ],
    }

    # Step 3: Build multi-epitope construct
    t0 = time.monotonic()
    construct: VaccineConstruct | None = None
    construct_data: dict = {}
    if b_cell_epitopes:
        candidates = [
            EpitopeCandidate(
                sequence=ep.sequence,
                source=pathogen_name,
                epitope_type="b_cell",
                score=ep.antigenicity_score,
                conservation=cr.conservation_score,
            )
            for ep, cr in zip(b_cell_epitopes, conservation_results)
        ]
        construct = build_multi_epitope_construct(candidates, linker=linker)
        construct_data = {
            "full_sequence": construct.full_sequence,
            "total_length": construct.total_length,
            "estimated_mw_kda": construct.estimated_mw_kda,
            "linker": linker,
            "signal_peptide": construct.signal_peptide,
            "n_epitopes": len(construct.epitopes),
        }
    results["steps"]["construct_builder"] = {
        "duration_s": round(time.monotonic() - t0, 4),
        **construct_data,
    }

    # Step 4: mRNA optimization
    t0 = time.monotonic()
    mrna_data: dict = {}
    if construct:
        mrna = optimize_mrna_construct(construct.full_sequence)
        mrna_data = {
            "coding_sequence_length": len(mrna.coding_sequence),
            "gc_content": mrna.gc_content,
            "codon_adaptation_index": mrna.codon_adaptation_index,
            "poly_a_length": mrna.poly_a_length,
            "utr5_length": len(mrna.utr5),
            "utr3_length": len(mrna.utr3),
        }
    results["steps"]["mrna_optimization"] = {
        "duration_s": round(time.monotonic() - t0, 4),
        **mrna_data,
    }

    results["total_duration_s"] = round(time.monotonic() - pipeline_start, 4)
    return results


# ---------------------------------------------------------------------------
# Vaccine design report
# ---------------------------------------------------------------------------

def build_vaccine_design_report(
    case_id: str | None,
    epitopes: list[dict],
    db: "Session | None" = None,
) -> dict:
    """Build a structured vaccine design report.

    STRONG DISCLAIMER: Research only. Requires clinical trials, ethics board
    approval, and regulatory clearance. Not for human or animal use.
    """
    ep_candidates = [
        EpitopeCandidate(
            sequence=ep.get("sequence", ""),
            source=ep.get("source", "unknown"),
            epitope_type=ep.get("epitope_type", "b_cell"),
            score=float(ep.get("score", 0.0)),
            conservation=float(ep.get("conservation", 0.0)),
        )
        for ep in epitopes
        if ep.get("sequence")
    ]

    construct: VaccineConstruct | None = None
    mrna: mRNAConstruct | None = None

    if ep_candidates:
        construct = build_multi_epitope_construct(ep_candidates)
        mrna = optimize_mrna_construct(construct.full_sequence)

    case_info: dict = {}
    if case_id and db is not None:
        from backend.app.models import Case
        case = db.get(Case, case_id)
        if case:
            case_info = {
                "case_id": case_id,
                "species": case.species.value if hasattr(case.species, "value") else str(case.species),
                "id": case.id,
            }

    return {
        "report_type": "vaccine_design",
        "case_info": case_info,
        "disclaimers": [
            VACCINE_DESIGN_DISCLAIMER,
            "DO NOT USE FOR CLINICAL PURPOSES.",
            "All sequences are computational predictions only.",
            "Immunogenicity, safety, and efficacy have not been validated.",
            "Regulatory approval is required before any human or animal administration.",
        ],
        "construct": {
            "full_sequence": construct.full_sequence if construct else None,
            "total_length": construct.total_length if construct else 0,
            "estimated_mw_kda": construct.estimated_mw_kda if construct else 0.0,
            "signal_peptide": construct.signal_peptide if construct else None,
            "n_epitopes": len(ep_candidates),
        },
        "epitope_table": [
            {
                "sequence": ep.sequence,
                "source": ep.source,
                "epitope_type": ep.epitope_type,
                "score": ep.score,
                "conservation": ep.conservation,
            }
            for ep in ep_candidates
        ],
        "mrna_stats": {
            "coding_sequence_length": len(mrna.coding_sequence) if mrna else 0,
            "gc_content": mrna.gc_content if mrna else 0.0,
            "codon_adaptation_index": mrna.codon_adaptation_index if mrna else 0.0,
            "poly_a_length": mrna.poly_a_length if mrna else 0,
        },
    }
