"""FoldAgent AlphaFold Module"""

from backend.app.alphafold.base import (
    AlphaFoldBackend,
    BackendMode,
    MockAlphaFoldBackend,
    StaticMetadataBackend,
    StructureInputManifest,
    StructureResult,
    get_backend,
    list_backends,
    register_backend,
)
from backend.app.alphafold.output_parsers import (
    STRUCTURE_EVIDENCE_KEYS,
    ParsedStructurePayload,
    extract_alphafold_structure_payload,
    extract_inline_structure,
    filter_structure_evidence,
    harvest_af3_output_dir,
    parse_alphafold_stdout,
)
from backend.app.alphafold.schemas import (
    # AF3 JSON input dialect models
    AF3InputJSON,
    AlphaFold2LocalJobRequest,
    AlphaFold3LocalJobRequest,
    AlphaFoldDbLookupRequest,
    AlphaFoldJobRequestBase,
    AlphaFoldServerJobRequest,
    BondAtomSpec,
    ColabFoldJobRequest,
    DnaEntity,
    DnaModification,
    LigandEntity,
    ProteinEntity,
    ProteinModification,
    ProteinTemplate,
    RnaEntity,
    RnaModification,
    SequenceEntry,
    parse_alphafold_request,
)

__all__ = [
    "AlphaFoldBackend",
    "BackendMode",
    "StructureInputManifest",
    "StructureResult",
    "MockAlphaFoldBackend",
    "StaticMetadataBackend",
    "register_backend",
    "get_backend",
    "list_backends",
    "AlphaFoldJobRequestBase",
    "AlphaFold3LocalJobRequest",
    "AlphaFold2LocalJobRequest",
    "AlphaFoldServerJobRequest",
    "AlphaFoldDbLookupRequest",
    "ColabFoldJobRequest",
    "parse_alphafold_request",
    # AF3 JSON input dialect models
    "AF3InputJSON",
    "BondAtomSpec",
    "DnaEntity",
    "DnaModification",
    "LigandEntity",
    "ProteinEntity",
    "ProteinModification",
    "ProteinTemplate",
    "RnaEntity",
    "RnaModification",
    "SequenceEntry",
    "STRUCTURE_EVIDENCE_KEYS",
    "ParsedStructurePayload",
    "extract_alphafold_structure_payload",
    "extract_inline_structure",
    "filter_structure_evidence",
    "harvest_af3_output_dir",
    "parse_alphafold_stdout",
]
